### ISSUE TITLE
Element is appearing in new line even though startWithNewLine: false is applied (Edge, IE11)

### ISSUE THREAD

**Issue by bappajubcse05** [surveyjs/surveyjs#1054]
### Are you requesting a feature, reporting a bug or ask a question?
Question/bug

### What is the current behavior?
Used survey builder to test the attached code. Here the question1 is having startWithNewLine: false and visibleIf condition which is dependent on question2 element's select me dropdown value. When the value is selected, question1 should appear in the same line with question3, which is not happening.

[Code is attached below]

### What is the expected behavior?

Question2 should appear in the same line with Question3

### How would you reproduce the current behavior (if this is a bug)?

Need to run the code in survey builder.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://surveyjs.io/published?id=4af84f74-59e9-41dc-bd93-2e34a989c1ca

Test code

```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "dropdown",
     name: "question2",
     choices: [
      "item1",
      "item2",
      {
       value: "item3",
       text: "select me"
      }
     ]
    },
    {
     type: "dropdown",
     name: "question3",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question1",
     visible: false,
     visibleIf: "{question2}='item3'",
     startWithNewLine: false,
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Firefox 52.1.0 (64-bit), IE11, Google Chrome v64
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: v1.0.16 /  v1.0.17

**Comment by andrewtelnov** [comment]
@bappajubcse05 It works fine for me: https://plnkr.co/edit/yl4Bkkndu4hiyeIa5dUk?p=preview

Thank you,
Andrew

**Comment by bappajubcse05** [comment]
Hello @andrewtelnov 

Tried the same link in IE-11, facing the same problem. attached screenshot. 

![survey-js](https://user-images.githubusercontent.com/34443377/38933999-121971f4-430a-11e8-935c-6267af34119a.JPG)

**Comment by andrewtelnov** [comment]
@bappajubcse05 Indeed there is an issue in MS Edge as well.

**Comment by dmitrykurmanov** [comment]
@bappajubcse05, hello!

this is ie specific bugs with `line-height` and `width:50%` (https://stackoverflow.com/a/5488983/6623551)
Thank you for founding it and post an issue.

We've fixed it. Fix will be available in the next minor update.

**Comment by bappajubcse05** [comment]
hello @dmitrykurmanov , The fix has introduced alignment issue. attached screenshot. 
![allignment issue](https://user-images.githubusercontent.com/34443377/39191662-f39edea0-47c6-11e8-8d90-8c6f25c1ccba.jpg)

**Comment by tsv2013** [comment]
@bappajubcse05 The issue is ralated to the incorrect size rounding issue in IE browsers. We implemented the recommended fix - set smaller width for IE browsers only. I do see the issue. Thank you for the report we'll try to find other solution.

**Comment by bappajubcse05** [comment]
Hello @andrewtelnov  I found the newline problem in Firefox and Chrome as well, it is not only on IE.


Here is the example -
If you select 'Select Me' from Question1 dropdown, the issue will be replicated.

https://surveyjs.io/Service/EditSurvey/6a13c1f8-74d6-419b-ae82-beb4362bedf4


Code is attached here -

```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "dropdown",
     name: "question1",
     choices: [
      "Select Me",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question3",
     visibleIf: "{question1} = 'Select Me'",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question4",
     visibleIf: "{question1} = 'Select Me'",
     startWithNewLine: false,
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}
```

**Comment by tsv2013** [comment]
@bappajubcse05 @andrewtelnov I've reproduced in Chrome on our site with 1.0.19. I'll take a look.

**Comment by bappajubcse05** [comment]
I think the fix is already released in 1.0.20 but I'm still facing the issue in my application. Trying capture the steps to replicate that.

**Comment by bappajubcse05** [comment]
@ dmitrykurmanov , @andrewtelnov  - This is not working when custom CSS is used in the survey to override "row" with "" (I,e, `"row": ""`).

**For example:**
```
("#xyz").Survey({
    model: survey,
    data: surveyData,
    css: myCustomCss});
```

**Comment by dmitrykurmanov** [comment]
@bappajubcse05 hello! If I understand you correctly to save this styles you could write same styles in your new class. Or you can just save an old class and add a new. For example:                 
                              `"row": "sv_row your_custom_class"`.

**Comment by bappajubcse05** [comment]
**I have followed :**  https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default

**Comment by dmitrykurmanov** [comment]
I am afraid that I don't  understand you. But My suggestion was something like that:
```JS
var myCss = {
   ...
   "row": "custom_row_class",
 ...
};
```

```CSS
.custom_row_class > div {
    margin-right: -0.285em
}

.custom_row_class > * {
    font-size: 1em;
}
```

**Comment by bappajubcse05** [comment]
Correct. But my question is that - can I assign empty (""), instead of "custom_row_class" in side the js as shown below -

```
var myCss = {
...
"row": "",
...
}
```

**Comment by tsv2013** [comment]
Default row class "sv_row" is used to implement built-in functionality of inline questions arrangement. If you remove this class, you simply drop this fuctionality. In this case you need to implement your own CSS customizations according to your requirements including inline questions arrangement.

If you add an additional CSS class as suggested @dmitrykurmanov, you can write your own more specific CSS selectior and add your custmozations.

If our solution doesn't fit your needs, please describe your task in greater details and we'll try to find a solution for you.

**Comment by bappajubcse05** [comment]
@tsv2013 - thank you. This clarified my query.
