### ISSUE TITLE
Microsoft Edge crashes when display range input

### ISSUE THREAD

**Issue by gurix** [surveyjs/surveyjs#1117]
### Are you requesting a feature, reporting a bug or ask a question?

A bug, only observed with Microsoft Edge at the moment

### What is the current behavior?

The browser crashes and reload the pages

### What is the expected behavior?

It is expected to display the page including the range input field.

### How would you reproduce the current behavior (if this is a bug)?

Using Microsoft Edge. Create a survey inlcuding a text field and change the `inputType` to `range`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/0v5VnrwSvvXJjN5ZhUg9?p=preview

Test code

```javascript
var json = {
    questions: [
        {
            name: "test",
            type: "text",
            inputType: "range"
        }
    ]
};

```

### Specify your

* browser: Microsoft Edge
* browser version: Microsoft Edge 41.16299.402.0 Microsoft EdgeHTML 16.16299. But also newer versions are affected and i guess also older. IE 11 seems to work so far.
* surveyjs platform (angular or react or jquery or knockout or vue): jquery@3.3.1
* surveyjs version: 1.0.23

**Comment by tsv2013** [comment]
Reproduced

**Comment by tsv2013** [comment]
MS Edge bug - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8696129/

**Comment by dmitrykurmanov** [comment]
and the fiddle from the ticket to reproduce: https://jsfiddle.net/ve088ofb/

**Comment by dmitrykurmanov** [comment]
This ticket at developer.microsoft.com created in 2016 and exists now. So we've fixed the issue, fix will be available in the next release.

**Comment by gurix** [comment]
Thanks, I cloned the repository, build the packages and it works now für Window Edge. Thanks for your fast response! 

Back in August 2017 they marked https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8696129/ as fixed, but it still failing with the least version 🤔That's really strange.
