### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the SurveyQuestion component.

### ISSUE THREAD

**Issue by b166er** [surveyjs/surveyjs#1433]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
warning-message in console

### What is the expected behavior?
no warnings

### How would you reproduce the current behavior (if this is a bug)?
check any option at first page, click "Next", then click "Previous", select first option "Windows" -> you get the warning message.

#### Provide the test code and the tested page URL (if applicable)
Test code:
```
Survey
    .StylesManager
    .applyTheme("bootstrap");
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";

var json = {
pages: [
{
	title: "What operating system do you use?",
	questions: [
		{
			type: "checkbox",
			name: "opSystem",
			title: "OS",
			isRequired: true,
			choices: ["Windows", "Linux", "Macintosh OSX"]
		}
	]
}, {
	title: "What language(s) are you currently using?",
	visibleIf: "{opSystem} contains 'Windows'",
	questions: [
		{
			type: "checkbox",
			name: "langs",
			title: "Plese select from the list",
			isRequired: true,
			visibleIf: "{opSystem} contains 'Windows'",
			choices: [
				"Javascript",
				"Java",
				"Rust",
				"PowerShell"
			]
		}
	]
}, {
	title: "What Car are you currently using?",
	visibleIf: "{langs} contains 'Java'",
	questions: [
		{
			type: "checkbox",
			name: "car",
			title: "Plese select from the list",
			isRequired: true,
			choices: [
				"Test1",
				"Test2",
				"Test3",
				"Test4"
			]
		}
	]
}, {
	title: "Please type your data",
	questions: [
		{
			type: "text",
			name: "name",
			title: "Name:"
		}, {
			type: "text",
			name: "email",
			title: "Your e-mail"
		}
	]
}]};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .innerHTML = "result: " + JSON.stringify(result.data);
    });

ReactDOM.render(<Survey.Survey model={survey}/>, document.getElementById("surveyElement"));

```

### Specify your

* browser: Google Chrome
* browser version: 70
* surveyjs platform: react
* surveyjs version: v15.6.2

**Comment by dmitrykurmanov** [comment]
Hello! Could you please clarify what version of the SurveyJS do you use? (I think that 15.6.2 is react version). 
We've fixed that bug several days ago. Please try the latest SurveyJS (1.0.54)

**Comment by b166er** [comment]
yes you right, i'm using Survej v1.0.54! and thanks for the info, that's good news!

**Comment by dmitrykurmanov** [comment]
Is the bug reproduced in the 1.0.54 version?

**Comment by b166er** [comment]
> Is the bug reproduced in the 1.0.54 version?

yes, i still have the warning-messsage, just try my example page from above.

**Comment by b166er** [comment]
> Fix will be available in the next minor update, most likely today.

thank you!
